language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.6"
  - DJANGO="django==1.5"
  - DJANGO="django==1.4.2"

install:
 - pip install -r requirements/external_apps.txt --use-wheel
 - pip install -r requirements/test_apps.txt --use-wheel
 - pip install coverage coveralls --use-wheel
 - pip install $DJANGO --use-wheel

script:
  - coverage run --source=basic_email setup.py test

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.2"
    - python: "3.4"
      env: DJANGO="django==1.4.2"
    - python: "2.6"
      env: DJANGO="django==1.7"

after_success:
  - coverage report --omit="basic_email/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@arabel.la
